name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  example:
    aliases: ["ex"]
    description: "This is an example plugin."
  info:
    aliases: ["information"]
    description: "Información del servidor"
  rank:
    description: "Editor de rangos (solo administradores)"