name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  information:
    description: "Información general del servidor"
  rank:
    description: Editor de rangos
    permission-message: No tienes permiso para usar este comando
  go:
    usage: /<command> [7-seg | alu | 14-seg]
    description: "Comando para teletransortarse a lugares representativos"
  login:
    usage: /