name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  info:
    aliases: ["information"]
    description: "Información general del servidor"
  rank:
    description: "Editor de rangos (solo administradores)"
  go:
    description: "Comando para teletransortarse a lugares representativos"